### ISSUE TITLE
Thread database model

### ISSUE THREAD

**Issue by codes4coffee** [codes4coffee/nebula#10]

**Comment by josh-127** [comment]
I forgot to reference this issue in my commit messages, so I'll post the commit links here:
- [Add unit tests for DbThreadDao](https://github.com/codes4coffee/nebula/commit/1217b82b1f7444bc99c553b2883c28a79abba2ca)
- [Redefine ThreadDao interface for correctness/safety](https://github.com/codes4coffee/nebula/commit/27ce917bef42485b0ba6efbc1f5b5ed26eca02f2)
- [ThreadDao::postThread will add existing comments](https://github.com/codes4coffee/nebula/commit/b016ae29cd916519a3d6c023bf89a512524ba1c6)
- [Add data access object for threads](https://github.com/codes4coffee/nebula/commit/6ac6c68be24b0dbc8f93935b0b285c6748dc4094)
